### ISSUE TITLE
Lädt nicht alle Bilder

### ISSUE THREAD

**Issue by HDsports** [zero-24/plg_content_imagelazyloading#1]
Danke für das Plugin.
Allerdings habe ich das Problem, dass das Plugin dann einige Bilder gar nicht lädt.

Hier ein Beispiel
https://www.hdsports.at/marathon/die-25-schoensten-marathons-der-welt
Bei einigen Bildern wird nur die Caption angezeigt, aber nicht das Bild. Wenn das Plugin deaktiviert ist, werden alle Bilder geladen
![ex](https://user-images.githubusercontent.com/12660317/167275756-b13576a0-6631-47ef-ab90-38d3f48eea2e.png)
.

**Comment by zero-24** [comment]
Hmm interessant hatte ich so noch nicht. Versuche einmal bitte die width & height attribute zu setzen, wie hier vorgeschalgen: 
https://web.dev/browser-level-image-lazy-loading/#images-should-include-dimension-attributes

**Comment by HDsports** [comment]
Hallo Tobias,

danke, ich glaube das war wahrscheinlich der Grund. Normalerweise werden die Attribute ja im Editor automatisch gesetzt, aber die fehlten tatsächlich. Nun wird es korrekt angezeigt.

 

Liebe Grüße, Thomas


________________________________________________________________________
HDsports – Home of Distance Runners & Mountain Lovers
Badergasse 239/2
A-6465 Nassereith
www.HDsports.at <https://www.hdsports.at/>  // HDsports.de  
Laufkalender / Triathlonkalender / Gesundheits-, Ernährungs- und Trainingstipps / Laufschuh-Finder / Laufuhren- und Laufband-Übersicht / Sportnahrungs-Datenbank / Skigebiete-Finder / Bergtouren-Finder / Laufshop / Virtuelle Laufevents

 

Von: Tobias Zulauf ***@***.***> 
Gesendet: Sonntag, 8. Mai 2022 02:32
An: zero-24/plg_content_imagelazyloading ***@***.***>
Cc: HDsports ***@***.***>; Author ***@***.***>
Betreff: Re: [zero-24/plg_content_imagelazyloading] Lädt nicht alle Bilder (Issue #1)

 

Hmm interessant hatte ich so noch nicht. Versuche einmal bitte die width & height attribute zu setzen, wie hier vorgeschalgen:
https://web.dev/browser-level-image-lazy-loading/#images-should-include-dimension-attributes

**Comment by zero-24** [comment]
Top mache dann das Ticket hier zu.
