### ISSUE TITLE
iframe lazy-loading

### ISSUE THREAD

**Issue by 4digitalworld** [zero-24/plg_content_imagelazyloading#3]
Since all modern browsers support lazy loading for iframes, you could add support for the `lazy-loading` attribute in the plugin settings.

example:

`<iframe src="https://example.com" loading="lazy" width="600" height="400"></iframe>`

this plugin was released in 2020 when lazy loading was only supported for images, now in 2024 lazy loading is also supported for iframes, so I think it's time to add iframe support to this plugin!

**read more:** 
[https://web.dev/articles/iframe-lazy-loading](https://web.dev/articles/iframe-lazy-loading)
[https://caniuse.com/loading-lazy-attr](https://caniuse.com/loading-lazy-attr)

![image](https://web.dev/static/articles/iframe-lazy-loading/image/data-savings-using-ifram-721849ff3b329_856.png)
![image](https://web.dev/static/articles/iframe-lazy-loading/image/chromecom-achieved-10-s-80c4aa3655294_856.png)

**Comment by zero-24** [comment]
Hi, yes i know I'm not sure whether it is actually needed here given that the core does have support for that loading attribute too, that was not the case back when this extension was created. So do you have a usecases where we would need support via this plugin that can not be covered via the core features?

**Comment by 4digitalworld** [comment]
> the core does have support for that loading attribute too

as far as i know your plugin [was](https://magazine.joomla.org/all-issues/january-2021/using-native-lazyloading-on-your-website) originally part of @Joomla core but then it was removed from Joomla.
is there a setting in Joomla now to automatically add this attribute to `images` and `iframes`?

> So do you have a usecases where we would need support via this plugin that can not be covered via the core features?

my website has thousands of articles created before **Joomla 4** and most of the articles have embedded YouTube player and other iframes that currently don't have the `loading="lazy"` attribute, so I need a solution that will automatically add the `loading="lazy"` attribute to all iframes on my website.

as far as i know your plugin automatically adds `loading="lazy"` attribute to `images` and it works great and i need the same for `iframes` to speed up loading of thousands of pages on my website.

**Comment by zero-24** [comment]
> as far as i know your plugin [was](https://magazine.joomla.org/all-issues/january-2021/using-native-lazyloading-on-your-website) originally part of https://github.com/joomla core but then it was removed from Joomla.

It was never shipped in a stable version but it was shortly part of the core thats right. When you check the article there we also mention that we have removed this in favor of a core version to add it. The plugin is only needed to have an easy backport to existing sites.

> my website has thousands of articles created before Joomla 4 and most of the articles have embedded YouTube player and other iframes that currently don't have the loading="lazy" attribute, so I need a solution that will automatically add the loading="lazy" attribute to all iframes on my website.

Wouldnt it not be easier to run an sql script over the content to solve this for the "older" articles? Like search and replace `<iframe ` and replace that with `<iframe loading="lazy" ` (both with extra space at the end)

But I have just released this version which also has optional support for iframe lazyloading: https://github.com/zero-24/plg_content_imagelazyloading/releases/tag/1.0.3

**Comment by 4digitalworld** [comment]
> But I have just released this version which also has optional support for iframe lazyloading: https://github.com/zero-24/plg_content_imagelazyloading/releases/tag/1.0.3

Thank you! this will help as a temporary solution while I update my old website!

> Wouldnt it not be easier to run an sql script over the content to solve this for the "older" articles? Like search and replace `<iframe ` and replace that with `<iframe loading="lazy" ` (both with extra space at the end)

I have several thousand articles on my website, I think it will be very problematic for my VPS if I run such a script through the database.
